### ISSUE TITLE
网页返回的公钥怎么用

### ISSUE THREAD

**Issue by xiahuaijia** [ScottZg/ZGRSAEncryptor#1]
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArWx6cnfc+Ugdu7CW5CtC
OeecZqBCUooQDvHxixCxMh5Tyjg1HTkAHW99Wu9Owo4mZ4L+Cj/wpQYDToyUNXGq
+OvvhnHSH50xc9fStMqu4SizbnLKr0j6DWWsONYK9Vst1ilBcrikZHBQ882qgETr
3M0ipvAJg6+4tXv5Pza/a4W+n+JmYfRZDgcldoHDj4COOeZZNP8RD41BZx0kAWr9
Mxt37xoujBnQiRlWV0Zzpy7DbnVE6TQhS2QT6w2Cjt0EF9Kw6BcIBxFYddlSaN2L
h7HVRuVnVVrjC2RUUaQmmKQd9m7H5VHDoYHArcJjWVMYrcrgYlBkIlBwUx/YjhNz
/wIDAQAB
-----END PUBLIC KEY-----

这个样子的

**Comment by ScottZg** [comment]
你在配SSH么

**Comment by xiahuaijia** [comment]
RSA 加密 字符串. 然后拿到 加密 的完文本
